#pragma once
#include "Arg/IntArg.hpp"
#include "Arg/EnumArg.hpp"
#include "Arg/JsonRawArg.hpp"
#include "Arg/StringArg.hpp"
#include "Arg/BoolArg.hpp"
#include "Arg/FlattedStringArrayArg.hpp"
#include "Responder/NormalResultResponder.hpp"
#include "Responder/EventResponder.hpp"